edit_mode = "vi"
skip_welcome_message = true
startup = ["zoxide init nushell --hook prompt | save ~/.cache/.zoxide.nu", "source ~/.cache/.zoxide.nu"]

[env]
EDITOR = "nvim"

[line_editor]
completion_type = "list"
edit_mode = "vi"

[textview]
use_italics = true
